config/routes.rb
Lenses::Application.routes.draw do
  devise_for :users

  resources :lenses

  root :to => 'lenses#index'

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  attr_accessible :name
  has_many :lenses

  def find_or_create_by_code!(name)
    b = Brand.find_by_lense_type(name)
    unless b
      b=Brand.new
      b.name=name
      b.save
    end
    b
  end

end

app/models/lense.rb
class Lense < ActiveRecord::Base
  attr_accessible :brand_id, :lense_type_id, :max_aperture, :max_focal_length, :min_aperture, :min_focal_length, :name, :notes, :lense_type, :brand


  belongs_to :lense_type
  belongs_to :brand

  validate :max_aperture_larger_min_aperture
  validate :max_focal_length_larger_min_focal_length

  validates :name, presence: true, uniqueness: true
  validates :brand, presence: true
  validates :lense_type, presence: true
  validates :min_aperture, presence: true, numericality: {greater_than: 0}
  validates :max_aperture, presence: true, numericality: {greater_than: 0}
  validates :max_focal_length, presence: true, numericality: {greater_than: 0}
  validates :min_focal_length, presence: true, numericality: {greater_than: 0}

  def max_aperture_larger_min_aperture
    errors.add(:max_aperture, "max_aperture must be equal or larger than min_aperture.") if self.max_aperture && self.min_aperture && self.max_aperture < self.min_aperture
  end

  def max_focal_length_larger_min_focal_length
    errors.add(:max_focal_length, "max_focal_length must be equal or larger than min_focal_length.") if self.max_focal_length && self.min_focal_length && self.max_focal_length < self.min_focal_length
  end


  #def self.search(search_params)
  #  lt = LenseType.find(search_params[:lense_type_selection]).lense_type
  #  at = search_params[:aperture_to].blank? ? 36 : search_params[:aperture_to]
  #  min_fl = search_params[:min_focal_length].blank? ? 0 : search_params[:min_focal_length]
  #  max_fl = search_params[:max_focal_length].blank? ? 2000 : search_params[:max_focal_length]
  #
  #  find(:all, conditions: ['lense_types.lense_type LIKE ? and max_focal_length <= ? and min_focal_length >= ? and min_aperture <= ? ',
  #                          "%#{lt}%",
  #                          "#{max_fl}",
  #                          "#{min_fl}",
  #                          "#{at}"],
  #       :joins => [:lense_type])
  #end


end

app/models/lense_type.rb
class LenseType < ActiveRecord::Base
  attr_accessible :lense_type
  has_many :lenses

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/lenses_controller.rb
class LensesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  # GET /lenses
  # GET /lenses.json
  def index

    if params[:lense_type_selection].present?
      @lenses = Lense.search(params)
    else
      @lenses = Lense.all
    end
    @lense_types = LenseType.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lenses }
    end
  end

  # GET /lenses/1
  # GET /lenses/1.json
  def show
    @lense = Lense.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lense }
    end
  end

  # GET /lenses/new
  # GET /lenses/new.json
  def new
    @lense = Lense.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lense }
    end
  end
  def index
    @photos = get_flickr_pictures()
  end

  # GET /lenses/1/edit
  def edit
    @lense = Lense.find(params[:id])
  end

  # POST /lenses
  # POST /lenses.json
  def create
    @lense = Lense.new(params[:lense])

    respond_to do |format|
      if @lense.save
        format.html { redirect_to root_path, notice: 'Lense was successfully created.' }
        format.json { render json: @lense, status: :created, location: @lense }
      else
        format.html { render action: "new" }
        format.json { render json: @lense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lenses/1
  # PUT /lenses/1.json
  def update
    @lense = Lense.find(params[:id])

    respond_to do |format|
      if @lense.update_attributes(params[:lense])
        format.html { redirect_to @lense, notice: 'Lense was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lenses/1
  # DELETE /lenses/1.json
  def destroy
    @lense = Lense.find(params[:id])
    @lense.destroy

    respond_to do |format|
      format.html { redirect_to lenses_url }
      format.json { head :no_content }
    end
  end

  private
    def get_flickr_pictures
      FlickRaw.api_key="8fa76ef7873d2eac9c08e7773838a19c"
      FlickRaw.shared_secret="0d534faad9611d07"
      @photos = {}
      flickr.photos.search(:user_id => "26276803@N05", :tags => 'carousel').each do |p|
        info = flickr.photos.getInfo(:photo_id => p.id) # retrieve additional details
                                                        # p info # uncomment to see other details
        title = info.title
        square_url = FlickRaw.url_s(info)
        original_url = FlickRaw.url_o(info)
        taken = info.dates.taken
        views = info.views
        tags = info.tags.map {|t| t.raw}
        @photos[title]= FlickRaw.url_b(info)
      end
      return @photos
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lenses_helper.rb
module LensesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lenses</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="pull-left container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Lenses</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Search  Lenses", '#' %></li>
          <li><%= link_to "Browse Lenselist" %></li>
          <li><%= link_to "Contact Us" %></li>
          <li><%= link_to "Cart" %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span9">
          <%= yield %>
        </div>
        <div class="span3">
          <table>
          <% if user_signed_in? %>
                <tr><td>Hello Adminuser!</td></tr>
                <tr><td><%= link_to "Edit profile", edit_user_registration_path %></td></tr>
                <tr><td><%= link_to "Logout", destroy_user_session_path, method: :delete %></td></tr>
          <% else %>
                <tr><td><%= link_to "Sign up", new_user_registration_path %></td></tr>
                <tr><td><%= link_to "Admin Login", new_user_session_path %></td></tr>
              <!--navigation does here-->
          <% end %>
          </table>
        </div>
      </div>
    </div>


</body>
</html>

app/views/lenses/_form.html.erb
<%= simple_form_for @lense, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @lense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lense.errors.count, "error") %> prohibited this lense from being saved:</h2>

      <ul>
      <% @lense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <%= f.association :brand, label: "Brand" %>
    <%= f.association :lense_type,  :label_method => :lense_type, :value_method => :id, :include_blank => false %>
    <%= f.input :max_aperture, as: :string %>
    <%= f.input :min_aperture, label: "Minimum Aperture", as: :string %>
    <%= f.input :max_focal_length, label: "Maximum Focal Length", as: :string %>
    <%= f.input :min_focal_length, label: "Minimum Focal Length", as: :string %>
    <%= f.input :name, label: "Lens Name" %>
    <%= f.input :notes, label: "Notes" , as: :text%>
    <%= f.submit %>
  </div>
<% end %>

app/views/lenses/edit.html.erb
<h1>Editing lense</h1>

<%= render 'form' %>

<%= link_to 'Show', @lense %> |
<%= link_to 'Back', lenses_path %>

app/views/lenses/index.html.erb
<h1>Listing lenses waiting for bootstrap</h1>

<!--<%= form_tag lenses_path, :method => 'get' do %>
    <p>
      <%= select_tag "lense_type_selection", options_from_collection_for_select(@lense_types, "id", "lense_type", selected= params[:lense_type_selection]) %>
      <%= text_field_tag "aperture_to", value = params[:aperture_to] %>
      <%= text_field_tag "min_focal_length", value = params[:min_focal_length] %>
      <%= text_field_tag "max_focal_length", value = params[:max_focal_length] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %> -->

<table id="lenses">
  <thead>
  <tr>
    <th>Brand</th>
    <th>Name</th>
    <th>Max aperture</th>
    <th>Min aperture</th>
    <th>Max focal length</th>
    <th>Min focal length</th>
    <th>Notes</th>
    <th>Lense type</th>

  </tr>
  </thead>
  <tbody>
  <% @lenses.each do |lense| %>

      <tr onclick='document.location.href="<%= url_for(lense)%>"' style="cursor: pointer;">
        <td><%= lense.brand.name %></td>
        <td><%= lense.name %></td>
        <td><%= lense.max_aperture %></td>
        <td><%= lense.min_aperture %></td>
        <td><%= lense.max_focal_length %></td>
        <td><%= lense.min_focal_length %></td>
        <td><%= lense.notes %></td>
        <td><%= lense.lense_type.lense_type %></td>
        <% if user_signed_in? %>
        <td><%= link_to 'Edit', edit_lense_path(lense) %></td>
        <td><%= link_to 'Destroy', lense, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>

<br/>

<%= link_to 'New Lense', new_lense_path if user_signed_in? %>




<%= debug(params) %>

app/views/lenses/new.html.erb
<h1>New lense</h1>

<%= render 'form' %>

<%= link_to 'Back', lenses_path %>

app/views/lenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Brand:</b>
  <%= @lense.brand_id %>
</p>

<p>
  <b>Max aperture:</b>
  <%= @lense.max_aperture %>
</p>

<p>
  <b>Min aperture:</b>
  <%= @lense.min_aperture %>
</p>

<p>
  <b>Max focal length:</b>
  <%= @lense.max_focal_length %>
</p>

<p>
  <b>Min focal length:</b>
  <%= @lense.min_focal_length %>
</p>

<p>
  <b>Name:</b>
  <%= @lense.name %>
</p>

<p>
  <b>Notes:</b>
  <%= @lense.notes %>
</p>

<p>
  <b>Lense type:</b>
  <%= @lense.lense_type_id %>
</p>


<%= link_to 'Edit', edit_lense_path(@lense) %> |
<%= link_to 'Back', lenses_path %>